modules = [
  "ugrd.kmod.nosound",
  "ugrd.kmod.novideo",
  "ugrd.kmod.nonetwork"
]

kmod_ignore = [
'kvm', 'kvm_amd', 'kvm_intel',  # virtualization
'ch341', 'cp210x', 'joydev', 'binfmt_misc', 'wmi', 'xpad',  # misc
'coretemp', 'x86_pkg_temp_thermal', 'k10temp', 'x86_pkg_temp_thermal',  # thermal
'iTCO_wdt', 'iTCO_vendor_support', 'sp5100_tco',  # watchdog
'intel_qat', 'intel_powerclamp', 'intel_cstate', 'rapl', 'intel_rapl_common', 'intel_rapl_msr', 'intel_pmc_bxt',  #intel
'i2c_piix4', 'spi_intel_pci', 'i2c_ismt', 'i2c_i801'  # i2c
]
