binaries = [ "cryptsetup" ]

kmod_init = [ "dm_crypt" ]

cryptsetup_retries = 5
cryptsetup_autoretry = true

cryptsetup_keyfile_validation = true

[imports.config_processing]
"ugrd.crypto.cryptsetup" = [ "_process_cryptsetup_multi", "_process_cryptsetup_key_types_multi" ]

[imports.build_pre]
"ugrd.crypto.cryptsetup" = [ "detect_argon2" ]

[imports.build_tasks]
"ugrd.crypto.cryptsetup" = [ "export_crypt_sources" ]

[imports.init_main]
"ugrd.crypto.cryptsetup" = [ "crypt_init" ]

[imports.functions]
"ugrd.crypto.cryptsetup" = [ "get_crypt_dev" ]

[cryptsetup_key_types.keyfile]
key_command = "cat {key_file} |"

[custom_parameters]
cryptsetup_key_type = "str"  # The default key type to use for unlocking devices
cryptsetup_keyfile_validation = "bool"  # Whether to validate the key file
cryptsetup_key_types = "dict"  # Dict containing key types and their associated mount commands
cryptsetup_retries = "int"  # Number of times to retry unlocking a device
cryptsetup_prompt = "bool"  # Whether to prompt the user to press enter before unlocking devices
cryptsetup_autoretry = "bool"  # Whether to automatically retry unlocking devices
cryptsetup_trim = "bool"  # Adds the --allow-discards option to cryptsetup commands
cryptsetup = "dict"  # Dict of cryptsetup volume to be unlocked, keyed by mapped device name
argon2 = "bool"  # Whether or not argon2 is available
