tmpdir = "/tmp"
build_dir = "initramfs_build"
_build_log_level = 10
out_dir = "/tmp/initramfs_out"
clean = true
find_libgcc = true
hostonly = true
validate = true
library_paths = [ "/lib64" ]
old_count = 1

binaries = [ "/bin/bash" ]

[nodes.console]
mode = 0o644
major = 5
minor = 1

[imports.config_processing]
"ugrd.base.core" = [ "_process_build_logging",
		     "_process_out_file",
		     "_process_binaries_multi",
		     "_process_dependencies_multi",
		     "_process_opt_dependencies_multi",
		     "_process_xz_dependencies_multi",
		     "_process_gz_dependencies_multi",
		     "_process_copies_multi",
		     "_process_symlinks_multi",
		     "_process_nodes_multi",
		     "_process_paths_multi",
		     "_process_masks_multi",
		     "_process_hostonly",
		     "_process_validate",
		   ]

[imports.build_pre]
"ugrd.base.core" = [ "detect_tmpdir", "clean_build_dir", "find_libgcc" ]

[imports.build_deploy]
"ugrd.base.core" = [ "generate_structure",
		     "deploy_dependencies",
		     "deploy_xz_dependencies",
		     "deploy_gz_dependencies",
		     "deploy_copies",
		     "deploy_nodes",
		     "deploy_symlinks" ]

[imports.build_final]
"ugrd.base.core" = [ "handle_usr_symlinks" ]

[custom_parameters]
hostonly = "bool"  # If true, the initramfs will be built specifically for the host building it
validate = "bool"  # If true, the configuration of the initramfs will be validated against the host
_custom_init_file = "str"  # Add the _custom_init_file propety, used to set where the custom init file is located
tmpdir = "Path"  # The base directory for builds
build_dir = "Path"  # The directory where the initramfs is built
build_logging = "bool" # If true, additional build information will be logged to the console
_build_log_level = "int"  # The level of logging to use for the build log, set to 10 by default and incremeted by if build_log is true (min 20)
symlinks = "dict"  # Symlinks dict, defines the symlinks to be made in the initramfs
dependencies = "NoDupFlatList"  # Dependencies, used to define the dependencies of the initramfs
opt_dependencies = "NoDupFlatList"  # Optional dependencies, which will be included if they are found
xz_dependencies = "NoDupFlatList"  # XZipped dependencies property, used to define the xzipped dependencies (will be extracted)
gz_dependencies = "NoDupFlatList"  # GZipped dependencies property, used to define the gzipped dependencies (will be extracted)
library_paths = "NoDupFlatList"  # library_paths property, used to define the library paths to add to LD_LIBRARY_PATH
find_libgcc = "bool"  # If true, the initramfs will search for libgcc_s.so.1 and add it to the initramfs
binaries = "NoDupFlatList"  # Binaries which should be included in the intiramfs, dependencies resolved with lddtree
copies = "dict"  # Copies dict, defines the files to be copied to the initramfs
nodes = "dict"  # Nodes dict, defines the device nodes to be created
paths = "NoDupFlatList"  # Paths to be created in the initramfs
masks = "dict"  # Imports to be masked in the initramfs
out_dir = "Path"  # The directory where the initramfs is packed/output. If no packer is used, this is the final output directory.
out_file = "str"  # The name of the output file, if absolute, overrids out dir with the path, and sets out_file to the filename
old_count = "int"  # The number of times to cycle old files before deleting
clean = "bool"  # Add the clean property, used to define if the mounts should be cleaned up after boot
