
binaries = ['plymouthd', 'plymouth', 'plymouth-set-default-theme']

paths = ['/run/plymouth']

[imports.build_pre]
"ugrd.base.plymouth" = [ "prepare_files" ]

[imports.init_main]
"ugrd.base.plymouth" = [ "start_plymouth" ]
