# This configuration should autodetect root/luks info and use detached headers

modules = [
  "ugrd.kmod.standard_mask",
  "ugrd.crypto.cryptsetup"
]

# Wait a few seconds for storage to settle after modules are loaded if external or slow storage is used
#mount_wait = true
#mount_timeout = 3

auto_mounts = ['/boot']  # Automatically create mount config for /boot on the host

[cryptsetup.root]
header_file = "/boot/luks_header.img"
