# This config module will simply pull/load kmods from the running system

modules = [
  "ugrd.kmod.nosound",
  "ugrd.kmod.novideo",
  "ugrd.kmod.nonetwork",
]

# Optionally supply a kernel version, uses the current kernel version if not specified
#kernel_version = "6.1.53-gentoo-dist"
# Get host modules using lspci and lsmod
kmod_autodetect_lspci = true
kmod_autodetect_lsmod = true
