modules = [ 'ugrd.fs.cpio', 'ugrd.base.banner' ]  # get_archive_path
paths = ['dev', 'sys', 'proc']

test_image_size = 16
shebang = "#!/bin/bash"

check_cpio = false

[masks]
pack = "make_cpio"

[imports.build_pre]
"ugrd.fs.test_image" = ["init_banner"]

[imports.pack]
"ugrd.fs.test_image" = ["make_test_image"]

[custom_parameters]
shebang = "str"  # Add the shebang property, because the test mode disables the base module
mounts = "dict"  # We only need the mounts dict, not the whole module
test_image_size = "int"  # Define the size of the test image in MiB
test_flag = "str"  # Define the success flag used to determine if the test was successful

